[project]
name = "pinns"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "notebook>=7.4.7",
    "scikit-learn>=1.7.2",
    "scipy-stubs==1.16.2.0",
    "tqdm>=4.67.1",
]
